# Generated by Django 3.2.7 on 2021-09-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queue_manager.taskmodel')),
            ],
        ),
    ]
